### ISSUE TITLE
 Cannot run "python3 setup.py build_ext"successfully using pytorch1.7

### ISSUE THREAD

**Issue by LEONHWH** [ethnhe/PVN3D#105]
GPU : RTX 3050Ti
CUDA: 11.0

I can't get through" python3 setup.py build_ext ", And the error"nvcc fatal   : Unsupported gpu architecture 'compute_86'" always appears.

Can someone tell me if this program can run under pytorch==1.7 or CUDA == 11.x by changing some parameters？

**Comment by HannahHaensen** [comment]
@LEONHWH any solution there yet?

**Comment by LEONHWH** [comment]
> @LEONHWH any solution there yet?

If you have CUDA 11.0, you can try this command  `export TORCH_CUDA_ARCH_LIST="8.0"` before build. if you have Higher version such as CUDA 11.3, we don't need that.

**Comment by HannahHaensen** [comment]
@LEONHWH 
how do you installed pcl? cause for me now with cuda 11.3 everything else works, but pcl install failed and using the conda install of pcl leads to an old torch distribution somwhow, very weird.

**Comment by LEONHWH** [comment]
> @LEONHWH how do you installed pcl? cause for me now with cuda 11.3 everything else works, but pcl install failed and using the conda install of pcl leads to an old torch distribution somwhow, very weird.

I install python-pcl from source 
# install dependencies
`sudo apt install libpcl-dev libvtk6-dev`
# clone fork with fix for Ubuntu 18.04
`git clone https://github.com/Tuebel/python-pcl`
`cd python-pcl`
`python3 setup.py install`

**Comment by HannahHaensen** [comment]
@LEONHWH thanks I will try that
