### ISSUE TITLE
demo file requisition

### ISSUE THREAD

**Issue by SanjunLiu** [ethnhe/PVN3D#11]
Could you help to offer the "demo.py" to check the results by using the pretrained model?

**Comment by ethnhe** [comment]
You can simply download the pre-trained models and run the evaluation script to evaluate them following the evaluation instruction.

**Comment by SanjunLiu** [comment]
I have tried this script for testing, the result is very good. But what I mean is how to visualize 3D results like this slide on the Zhihu linking video, PVN3D: "https://zhuanlan.zhihu.com/p/94020758"

**Comment by tjufan** [comment]
I also have the same problem, could you release the code for visualizing 3D results?

**Comment by ethnhe** [comment]
The demo script for visualizing is added
