### ISSUE TITLE
fatal error: opencv2/highgui.hpp: No such file or directory

### ISSUE THREAD

**Issue by aghaphd** [ethnhe/PVN3D#119]
rastertriangle_so.cpp:2:10: fatal error: opencv2/highgui.hpp: No such file or directory
    2 | #include <opencv2/highgui.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I'm having this error; do you know how to solve it?

**Comment by WHHHHY** [comment]
hey，I had this problem too,Could you help me  how to fix it?Thx a lot.
