### ISSUE TITLE
when run python3 setup.py build_ext, some errors happen

### ISSUE THREAD

**Issue by djlbet123** [ethnhe/PVN3D#12]
Environment:  
      Ubuntu 16.04
      gcc 5.4.0
      g++ 5.4.0
when I try to   run  run python3 setup.py build_ext.  It said

./pvn3d/_ext-src/src/group_points.cpp:56:40: 
error: ‘AT_CHECK’ was not declared in this scope
     AT_CHECK(false, "CPU not supported");                                       ^
error: command 'gcc' failed with exit status 1

I have found so many ways to try to solve it.but it still didn't work.Please help me

**Comment by ethnhe** [comment]
The PointNet++ code is referred from https://github.com/erikwijmans/Pointnet2_PyTorch, which currently ONLY supported on the GPU using CUDA.

**Comment by djlbet123** [comment]
Actually,I have solved it.No matter what.Thank you

**Comment by theIone** [comment]
> Actually,I have solved it.No matter what.Thank you
Hello, I also met the same problem, could you please tell me how you solved it
