### ISSUE TITLE
Checkpoint File shared link not publicly accessable

### ISSUE THREAD

**Issue by saadehmd** [ethnhe/PVN3D#13]
Hi,

The share-point link for trained checkpoints keeps asking for user-access. Are they private? If yes, can you share them with saad.ahmad@tuni.fi ? I am trying to replicate your work for University research.It'll be very kind of you. Thanks in advance.

**Comment by ethnhe** [comment]
They are publically shared. You can try the onedrive link again or the newly added baiduyun link.
