### ISSUE TITLE
nvcc and gcc version

### ISSUE THREAD

**Issue by Ixion46** [ethnhe/PVN3D#16]
Hey guys, I have problems to get this awesome paper working. 
Could you please write which nvcc version and gcc version you used?

**Comment by jwojski** [comment]
Hello @Ixion46,
Currently, the code in the repository uses PyTorch 1.0.1, which can be installed with CUDA 9.0 or 10.0.
I was also able to run the code with PyTorch 1.5 and CUDA 10.1, but it requires some minor code fixes.
I don't think the different gcc version can be source of errors.
Let me know what your problems are. I will try to help.

**Comment by Ixion46** [comment]
I try to run the code in a conda environment and use pip3 install -r requirements.txt as mentioned. Then when I execute python3 setup.py build_Ext he tells me, that packages like torch and scipy are missing, even tho they should get install with the pip3 command. If I install them with conda I get a gcc error if I am not use extra_compile_args ( -ccbin=/usr/bin/gcc-5 ) for nvcc in the setup.py and run CC=/usr/bin/gcc-5 python3 setup.py build_ext , because it wont run with  gcc >= 6.  After this step, when I try to run the demo file I get this error :  ImportError: /media/hdd2/PVN3D/pvn3d/lib/pointnet2_utils/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

**Comment by jwojski** [comment]
Hello,
it looks like incompatible PyTorch and CUDA versions. Look at [PyTorch - get started](https://pytorch.org/get-started/previous-versions/)  and make sure you have installed the correct PyTorch version for your CUDA.

**Comment by Ixion46** [comment]
Thanks for the help, but I just built a singularity container now, because I also got other bugs like cv2 missing etc

**Comment by Ixion46** [comment]
It seems like it is an alternative to cv2 , I could delete it and the code would run ahead this point
