### ISSUE TITLE
Own Dataset

### ISSUE THREAD

**Issue by Michael187-ctrl** [ethnhe/PVN3D#18]
Hey Guys, great Code and Paper. I stumbled upon this a few weeks ago and got some really good results with the linemod classes. But now I want to try it for my own objects, can someone please explain the best way how to obtain the meshes , poses and so on for the training of my own dataset?
Greetings Michael

**Comment by ethnhe** [comment]
You can generate some synthesis data with render scripts like [pvnet_rendering](https://github.com/zju3dv/pvnet-rendering) and our [raster triangle](https://github.com/ethnhe/raster_triangle). For real data, you can read some dataset papers to see how they collect and label the data, like LineMOD, YCB-Video, tless, and so on. While it's not so easy to label the ground truth poses.
