### ISSUE TITLE
test time on ycb so slow

### ISSUE THREAD

**Issue by wuqua** [ethnhe/PVN3D#20]
Why  test  each picture takes about 1-2 seconds on the data set YCB? so slow。
env：ubuntu16, Quadro RTX 5000

**Comment by ethnhe** [comment]
During inference, it takes 0.17 seconds for network forward propagation, most of which spent on PointNet++, and 0.02 seconds for pose estimation of each object on an RTX 2080 Ti.  Each picture contains multi objects in the YCB dataset.
