### ISSUE TITLE
models_info.yml

### ISSUE THREAD

**Issue by Ixion46** [ethnhe/PVN3D#26]
Hey @ethnhe , thanks for your great Code.
I want to try PVN3D aswell with a Costum Dataset and saw another issue about the models_info.yml file. Can you explain where the values min_x , min_y , min_z and diameter come from?
Because the min_x , min_y and min_z are not equal with the min_x , min_y and min_z in the mesh-files for the linemod objects. And the diameter is also not the diagonal in the boundingboxes

**Comment by ethnhe** [comment]
As explained in that issue, the object info are referred from PVNet  https://github.com/zju3dv/pvnet/blob/master/lib/utils/data_utils.py

**Comment by Ixion46** [comment]
Hey @ethnhe  , thanks for your answer. Can you please tell me how to obtain the corners.txt files for the YCB-Dataset objects? I was not able to reproduce the same files from the .obj or .xyz files of the ycb-dataset.
Best Regards Ixion
