### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by jako-dev** [ethnhe/PVN3D#27]
Hi @ethnhe,
thanks again for your awesome work.

Do you have any code snippets or working code for a live demo (i.e. with a kinect). Would it even be possible?

Could you give me some hints?

Sorry if that's not an actual issue with the project.
Thank you very much.

**Comment by ethnhe** [comment]
We didn't write live demo scripts. But with the provided ```*demo.py``` and ```*dataset.py``` scripts, it's not hard to integrate them for a live demo. You only need to get the input RGBD images from a sensor, preprocess them with code in ```*dataset.py```, and then feed it into the model to get the result using code in ```*demo.py```.

**Comment by jako-dev** [comment]
Thank you.

**Comment by ghost** [comment]
Hi @jako-dev,
Did you manage to do a live demo ? do you have any code snippets or working code ?
Thank you very much for your time and consideration.
