### ISSUE TITLE
Pose Prediction 

### ISSUE THREAD

**Issue by jako-dev** [ethnhe/PVN3D#28]
Hi,

i trained PVN3D on my own dataset (generated with NDDS). I'm trying to visualize it with your demo.py script. It works, but the pose is wrong.
Here are some examples:

My Dataset:
![1](https://user-images.githubusercontent.com/46926800/85379309-ebae7b80-b53b-11ea-89ac-29dd079c3cfd.jpg)
![6](https://user-images.githubusercontent.com/46926800/85379349-f701a700-b53b-11ea-9aa8-d811b5201242.jpg)

Do you have any idea what could have gone wrong? If you need any more information about the dataset, just let me know.

I'd be really grateful if you could help me out.
Thank you

**Comment by jako-dev** [comment]
This is the training progress for 25 epochs.
Right now im only training on 5000 images, i know that the training process shows signs of overfitting after some time. 

=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 2465.2959      val: 1413.4992                                                                                                                                                      
acc_rgbd      --- train: 0.9880 val: 0.9934                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0156 val: 0.0076                                                                                                                                                                 
loss_target   --- train: 2791.7706      val: 1580.5666                                                                                                                                                      
loss          --- train: 2791.7706      val: 1580.5666                                                                                                                                                      
loss_ctr_of   --- train: 326.4436       val: 167.0522                                                                                                                                                       
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 1188.2770      val: 1351.0834                                                                                                                                                      
acc_rgbd      --- train: 0.9947 val: 0.9916                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0045 val: 0.0079                                                                                                                                                                 
loss_target   --- train: 1321.0635      val: 1498.5815                                                                                                                                                      
loss          --- train: 1321.0635      val: 1498.5815                                                                                                                                                      
loss_ctr_of   --- train: 132.7775       val: 147.4823                                                                                                                                                       
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 1134.5012      val: 1264.9654                                                                                                                                                      
acc_rgbd      --- train: 0.9944 val: 0.9951                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0045 val: 0.0042                                                                                                                                                                 
loss_target   --- train: 1255.6084      val: 1402.3557                                                                                                                                                      
loss          --- train: 1255.6084      val: 1402.3557                                                                                                                                                      
loss_ctr_of   --- train: 121.0981       val: 137.3818                                                                                                                                                       
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 1093.4649      val: 1031.7366                                                                                                                                                      
acc_rgbd      --- train: 0.9949 val: 0.9915                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0041 val: 0.0060                                                                                                                                                                 
loss_target   --- train: 1208.9531      val: 1146.3301                                                                                                                                                      
loss          --- train: 1208.9531      val: 1146.3301                                                                                                                                                      
loss_ctr_of   --- train: 115.4800       val: 114.5816                                                                                                                                                       
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 714.0938       val: 815.2544                                                                                                                                                       
acc_rgbd      --- train: 0.9958 val: 0.9958                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0034 val: 0.0036                                                                                                                                                                 
loss_target   --- train: 770.6466       val: 885.2205                                                                                                                                                       
loss          --- train: 770.6466       val: 885.2205                                                                                                                                                       
loss_ctr_of   --- train: 56.5460        val: 69.9589                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 623.0649       val: 742.3010                                                                                                                                                       
acc_rgbd      --- train: 0.9970 val: 0.9971                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0024 val: 0.0027                                                                                                                                                                 
loss_target   --- train: 658.6436       val: 793.6844                                                                                                                                                       
loss          --- train: 658.6436       val: 793.6844                                                                                                                                                       
loss_ctr_of   --- train: 35.5739        val: 51.3780                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 599.0452       val: 739.7885                                                                                                                                                       
acc_rgbd      --- train: 0.9973 val: 0.9966                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0021 val: 0.0029                                                                                                                                                                 
loss_target   --- train: 627.4811       val: 787.7871                                                                                                                                                       
loss          --- train: 627.4811       val: 787.7871                                                                                                                                                       
loss_ctr_of   --- train: 28.4316        val: 47.9929                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 589.2926       val: 736.9972                                                                                                                                                       
acc_rgbd      --- train: 0.9974 val: 0.9970                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0020 val: 0.0027                                                                                                                                                                 
loss_target   --- train: 614.4662       val: 784.9681                                                                                                                                                       
loss          --- train: 614.4662       val: 784.9681                                                                                                                                                       
loss_ctr_of   --- train: 25.1696        val: 47.9655                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 591.6787       val: 744.8695                                                                                                                                                       
acc_rgbd      --- train: 0.9974 val: 0.9961                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0020 val: 0.0032                                                                                                                                                                 
loss_target   --- train: 617.7697       val: 794.7899                                                                                                                                                       
loss          --- train: 617.7697       val: 794.7899                                                                                                                                                       
loss_ctr_of   --- train: 26.0870        val: 49.9140                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 596.7305       val: 720.2719                                                                                                                                                       
acc_rgbd      --- train: 0.9973 val: 0.9968                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0020 val: 0.0027                                                                                                                                                                 
loss_target   --- train: 624.8582       val: 768.7568                                                                                                                                                       
loss          --- train: 624.8582       val: 768.7568                                                                                                                                                       
loss_ctr_of   --- train: 28.1236        val: 48.4795                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 605.5412       val: 736.6753                                                                                                                                                       
acc_rgbd      --- train: 0.9974 val: 0.9960                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0021 val: 0.0031                                                                                                                                                                 
loss_target   --- train: 636.2212       val: 787.5063                                                                                                                                                       
loss          --- train: 636.2212       val: 787.5063                                                                                                                                                       
loss_ctr_of   --- train: 30.6758        val: 50.8247                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 608.3579       val: 742.6067                                                                                                                                                       
acc_rgbd      --- train: 0.9967 val: 0.9964                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0026 val: 0.0031                                                                                                                                                                 
loss_target   --- train: 640.6477       val: 794.7792                                                                                                                                                       
loss          --- train: 640.6477       val: 794.7792                                                                                                                                                       
loss_ctr_of   --- train: 32.2846        val: 52.1664                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 616.5103       val: 753.4431                                                                                                                                                       
acc_rgbd      --- train: 0.9970 val: 0.9965                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0023 val: 0.0030                                                                                                                                                                 
loss_target   --- train: 650.4147       val: 811.0971                                                                                                                                                       
loss          --- train: 650.4147       val: 811.0971                                                                                                                                                       
loss_ctr_of   --- train: 33.8998        val: 57.6480                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 619.5284       val: 792.1638                                                                                                                                                       
acc_rgbd      --- train: 0.9973 val: 0.9969                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0022 val: 0.0029                                                                                                                                                                 
loss_target   --- train: 654.1799       val: 847.0971                                                                                                                                                       
loss          --- train: 654.1799       val: 847.0971                                                                                                                                                       
loss_ctr_of   --- train: 34.6471        val: 54.9275                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 624.9006       val: 765.6416                                                                                                                                                       
acc_rgbd      --- train: 0.9969 val: 0.9959                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0024 val: 0.0039                                                                                                                                                                 
loss_target   --- train: 661.1129       val: 819.1834                                                                                                                                                       
loss          --- train: 661.1129       val: 819.1834                                                                                                                                                       
loss_ctr_of   --- train: 36.2075        val: 53.5341                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 628.8576       val: 791.8664                                                                                                                                                       
acc_rgbd      --- train: 0.9966 val: 0.9936                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0026 val: 0.0054                                                                                                                                                                 
loss_target   --- train: 665.7016       val: 850.9237                                                                                                                                                       
loss          --- train: 665.7016       val: 850.9237                                                                                                                                                       
loss_ctr_of   --- train: 36.8387        val: 59.0466                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 629.0481       val: 749.9888                                                                                                                                                       
acc_rgbd      --- train: 0.9965 val: 0.9953                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0028 val: 0.0038                                                                                                                                                                 
loss_target   --- train: 666.1361       val: 806.0634                                                                                                                                                       
loss          --- train: 666.1361       val: 806.0634                                                                                                                                                       
loss_ctr_of   --- train: 37.0824        val: 56.0670                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                            
=== Training Progress ===                                                                                                                                                                                   
loss_kp_of    --- train: 634.3096       val: 800.5372                                                                                                                                                       
acc_rgbd      --- train: 0.9968 val: 0.9951                                                                                                                                                                 
loss_rgbd_seg --- train: 0.0026 val: 0.0042                                                                                                                                                                 
loss_target   --- train: 672.5097       val: 853.9666                                                                                                                                                       
loss          --- train: 672.5097       val: 853.9666                                                                                                                                                       
loss_ctr_of   --- train: 38.1950        val: 53.4209

**Comment by ethnhe** [comment]
Don't know what's wrong with the provided information. You can first check if the input data is correct. By visualizing the sampled points from the scene, the keypoints of the object, and so on, using scripts we provide in ```*dataset.py```.

**Comment by jako-dev** [comment]
![train_rgb_screenshot_24 06 2020](https://user-images.githubusercontent.com/46926800/85547709-736cb680-b61e-11ea-82d5-e80087e917f0.png)
![nrm_map_screenshot_24 06 2020_2](https://user-images.githubusercontent.com/46926800/85547719-7667a700-b61e-11ea-95d2-a07657c5fe16.png)

Thats the visualization (ignore the green points), which seems to be correct, doesnt it?

**Comment by ethnhe** [comment]
The keypoints seem correct but why is there so much black region? 
Anyway, you can check if the input segmentation and keypoint offset are correct by using the GT segmentation and offset as input to the pose estimation module. If it works well, use GT segmentation and predicted offset or predicted segmentation and GT offset to check if the two modules of the model are well trained.

**Comment by jako-dev** [comment]
My bad, i filtered the background. this seems to be right now
![nrm_map_screenshot_24 06 2020_3](https://user-images.githubusercontent.com/46926800/85549928-bfb8f600-b620-11ea-8047-7bec9294fd70.png)
Ok, thanks i will try that.

**Comment by jako-dev** [comment]
I filtered the background, my bad. I changed it. It now looks like the linemod visualization.
Here is my last latest training loss. The loss for loss seems to be really high.
=== Training Progress ===                                                               
acc_rgbd      --- train: 0.9818 val: 0.9959                                                         
loss_kp_of    --- train: 462.4043       val: 409.4338                                               
loss_target   --- train: 494.3592       val: 429.5899                                               
loss_rgbd_seg --- train: 0.0453 val: 0.0116                                                         
loss          --- train: 494.3592       val: 429.5899                                               
loss_ctr_of   --- train: 31.8644        val: 20.1328

**Comment by ethnhe** [comment]
Yes, so I think your input data have some error, maybe the ground truth offset to the keypoints. Did you try the suggestion?

> you can check if the input segmentation and keypoint offset are correct by using the GT segmentation and offset as input to the pose estimation module. If it works well, use GT segmentation and predicted offset or predicted segmentation and GT offset to check if the two modules of the model are well trained.

**Comment by jako-dev** [comment]
Can you specify a little more on how to that?

**Comment by ethnhe** [comment]
The GT labels are those you get from the input data, saying kp_targ_ofst, ctr_targ_ofst and labels in ```demo.py```, use them to replace the predicted label & offset before calling ```cal_frame_poses*```. But make sure that they are in the same shape as the predicted one, maybe you should do permute operation.

**Comment by jako-dev** [comment]
Thank you very much. I will try and let you know

**Comment by jako-dev** [comment]
![1](https://user-images.githubusercontent.com/46926800/85576804-01559b00-b639-11ea-8919-b344e5f97b43.jpg)

Thats the result, when i use GT information and feed it into cal_frame_poses

`kp_targ_ofst = kp_targ_ofst.permute(0,2,1,3)
                #add axis
                ctr_targ_ofst = ctr_targ_ofst.unsqueeze(1)
                
                pred_cls_ids, pred_pose_lst = cal_frame_poses(
                        pcld[0], labels[0], ctr_targ_ofst[0], kp_targ_ofst[0], True,
                        config.n_objects, True
                )`

**Comment by ethnhe** [comment]
Yes, it seems there is something wrong with your input data, trace and fix it.

**Comment by KatharinaSchmidt** [comment]
@jako-dev, did you try to visualize your annotated data from NDDS with [NVDU](https://github.com/NVIDIA/Dataset_Utilities)? That was my way to check, wether my synthesized data are annotated correctly or not. 
Furthermore I am still interested in your solution to use the data, which you synthesized with NDDS. Since the provided code has no comments, for me it's hard to see where I have to adapt the pvn3d-code to my dataset.

**Comment by jako-dev** [comment]
I visualized the keypoints by myself. Also they seem to be correct since they get transformed and drawn correctly with my adapted NDDS dataset script for pvn3d. The RT matrix and K seem to be correct also.

I think the error comes from the calculation of the target_offset (calculated by adding the pcld with -1.0*keypoints). Since i think that keypoints are correct, it might be the (p)cld. I couldn‘t find the error yet unfortunately. The pcld gets calculated from the depth image if i understood correctly.

@ethnhe is the format of the depth image important (like every pixel is depth in mm, cm or something else?)
What about the cam_scale (is this the maximum depth of the image?)?

I will post some examples of my pcld, keypoints and target_offset arrays as soon as i‘m back at my computer, maybe you can spot some errors there.

Thank you.

**Comment by jako-dev** [comment]
I finally managed to fix the gt information. 
![9](https://user-images.githubusercontent.com/46926800/86130304-40299c00-bae4-11ea-818b-fef401faf4e9.jpg)
![4](https://user-images.githubusercontent.com/46926800/86130318-461f7d00-bae4-11ea-971f-88164486243a.jpg)

**Comment by KatharinaSchmidt** [comment]
@jako-dev Could you show us, how you fixed the wrong information? 
I still try to adapt the dataset.py script for my own dataset. By the way, how did you get the keypoints of your 3D modells?

**Comment by jako-dev** [comment]
@KatharinaSchmidt I used parts of the clean-pvnet repo code (especially handle_custom_dataset.py) to read the .ply file and create the corners.txt and the farthest.txt.
The wrong pose was due to an error coming from left-hand coordinate system and right-hand-coordinate system. I flipped the y-axis of the mesh_kps before feeding it into best_fit_transform. I had some more issues while debugging but can't recall all of them. As soon as i validated the training results and cleaned up the code i can send it to you / upload it to github or so

**Comment by Michael187-ctrl** [comment]
Would be really nice if you can upload it to github! I am following this thread every day :)

**Comment by Michael187-ctrl** [comment]
Hey Jako-Dev did you make progress and does it work properly now?

**Comment by jako-dev** [comment]
Yes, it's working okay. The results on my dataset are not so great, but i think everything seems to working as it should be. I can't find any more issues

**Comment by jako-dev** [comment]
I will upload it as soon as i can. it might take a few days

**Comment by Michael187-ctrl** [comment]
Thanks :)

**Comment by Ixion46** [comment]
@jako-dev , can you please tell me how to get the corners.txt files in the YCB-Dataset , for example https://github.com/ethnhe/PVN3D/tree/master/pvn3d/datasets/ycb/ycb_object_kps/004_sugar_box ?
Because I cant derive them from the .ply models like in the linemod Dataset, because the YCB only got .xyz and .obj and with both of them I get other values than in the corners.txt . Best regards Philipp

**Comment by jako-dev** [comment]
Sorry, i got the corners.txt by using the points from
the ply file.

**Comment by Ixion46** [comment]
Okay thank you @jako-dev, gonna try it the same way then. And the different farthest.txt's are all obtained with the farthest key point sampling algorithm and just differs in the number of used points , right?

**Comment by jako-dev** [comment]
@Ixion46  yes that seems to be it.

**Comment by Ixion46** [comment]
@jako-dev Really thank you for your great help. To use that code for my own objects isnt that easy for me, so I am happy that there are people that help.

**Comment by KatharinaSchmidt** [comment]
@jako-dev I have the same issue with wrong gt when I try to train with clean-pvnet. Did you take the rotation matrix from 'quaternion_xyzw' or the first 3x3 matrix from 'pose_transform'? 
If I understand you correct, you flipped the y-axis (of the location?) for 180°, so just multiply with -1, correct?
Also I want to ask, as if you changed the scale unit of location values?

**Comment by Ixion46** [comment]
@jako-dev or @KatharinaSchmidt is there still the possibility that one of you uploads his changes to github? Would be great

**Comment by KatharinaSchmidt** [comment]
@Ixion46 I created a fork of PVNet, there is my code for reading the pose out of .json-file and other data generated with NDDS.
[fork-repositroy](https://github.com/KatharinaSchmidt/clean-pvnet)

**Comment by ssh10032** [comment]
Hi, I have issue with applying NDDS custom dataset on PVN3D.
Could you teach me how to get camera rotation matrix and transformation matrix from Json file?
It would be very grateful if you teach me how :D

**Comment by ssh10032** [comment]
@jako-dev @KatharinaSchmidt Can I ask how to get RT matrix from NDDS annotation file(JSON)?

I got RT matrix using object's **pose_transform** value, and visualize keypoint on RGB Image but it seems not correct.

![12](https://user-images.githubusercontent.com/83348645/148331989-ecbd491d-c588-450b-9a03-347836233d23.png)


I also change coordinate system left handed(Unreal Engine 4) to right handed(PVN3D).
Here's my visualization results.

![linemod cat 회전](https://user-images.githubusercontent.com/83348645/148331666-c7abfde7-d05f-4471-b456-526a34bdf4eb.png)
![microwave 돌린거](https://user-images.githubusercontent.com/83348645/148331670-37f7304b-582d-4298-9c70-dca54a35d409.png)
![microwave 정면](https://user-images.githubusercontent.com/83348645/148331674-100352e3-20ec-4817-827c-374b18195ef2.png)


I read all of your github issues about RT matrix value, but can't get answer.
I've been struggling with this almost one months.
If you know something, please let me know.
Thank you.
