### ISSUE TITLE
Question about dataloader item_name

### ISSUE THREAD

**Issue by trevor-taeyeop** [ethnhe/PVN3D#38]
I have a simple question about dataloader. 

For example, item_name =  'data_syn/003759'
As I understand, this part should be changed **int(item_name[5:9])**  **->** **int(item_name[9:15])**
Could you comment about this?? 

https://github.com/ethnhe/PVN3D/blob/3cfcbe33880ffacb37a9862067d303d27e9fcf82/pvn3d/datasets/ycb/ycb_dataset.py#L186

**Comment by ethnhe** [comment]
In the YCB_Video dataset, only real data (```item_name[:8] != 'data_syn'```) with  ```int(item_name[5:9]) >= 60``` use ```ycb_K2```, all other data (synthethic data & reall data with   ```int(item_name[5:9]) < 60``` use ```ycb_K1```.
