### ISSUE TITLE
 How to test the fps of the program？

### ISSUE THREAD

**Issue by Apollo19971206** [ethnhe/PVN3D#39]
Hello author, may I ask how to test the fps of the program？
Can you tell me the general method? I'm doing a comparative test.
Thank you!

**Comment by ethnhe** [comment]
We simply set a time counter between the network forward and the model output to get the runtime. We run the whole test set and calculate the mean of runtime for each frame. The inference time is reported in our [paper](https://arxiv.org/pdf/1911.04231.pdf).

**Comment by weiyaowu-md** [comment]
> We simply set a time counter between the network forward and the model output to get the runtime. We run the whole test set and calculate the mean of runtime for each frame. The inference time is reported in our [paper](https://arxiv.org/pdf/1911.04231.pdf).

hello, I can't find the  runtime in your paper, I wonder know the how much fps in one 2080ti in the test phase! thanks a lot !
