### ISSUE TITLE
Is the test results normal?

### ISSUE THREAD

**Issue by pyni** [ethnhe/PVN3D#41]
Hi~
I use your training weights (ape_pvn3d_best.pth.tar) to test some results.
For the real images, the test results are quite awesome:
![Screenshot from 2020-08-27 09-28-09](https://user-images.githubusercontent.com/18031767/91373615-70be5580-e849-11ea-88b3-0ea6b559dc45.png)

But for rendered images, the results are shown as follows:
![Screenshot from 2020-08-27 09-35-44](https://user-images.githubusercontent.com/18031767/91373645-829ff880-e849-11ea-99ea-a882fa30d157.png)
![Screenshot from 2020-08-27 09-36-03](https://user-images.githubusercontent.com/18031767/91373649-859ae900-e849-11ea-8287-22f0885438d8.png)
For rendered images with real background, the results are shown as follows:

![Screenshot from 2020-08-27 09-38-49](https://user-images.githubusercontent.com/18031767/91373679-93506e80-e849-11ea-82ca-f975e9da8965.png)
![Screenshot from 2020-08-27 09-39-30](https://user-images.githubusercontent.com/18031767/91373684-95b2c880-e849-11ea-923e-28fe55d10012.png)
![Screenshot from 2020-08-27 09-39-02](https://user-images.githubusercontent.com/18031767/91373697-9d726d00-e849-11ea-9bdd-cc44eea21cde.png)

I am not sure whether the results are normal? And does your training weights( pvn3d_best.pth.tar) use rendered images for training?

**Comment by ethnhe** [comment]
- The training weights use rendered images for training.
- We didn't inference on the synthesis data. But since the validation set only contains real scene images, It's possible that the selected weights perform better on real data than synthesis data.
