### ISSUE TITLE
Problem with Training ,  class or object 'NoneType'

### ISSUE THREAD

**Issue by Ixion46** [ethnhe/PVN3D#42]
Hey @ethnhe , I have some problems while running the training for my own dataset. I think I adjusted the dataset in the correct way so that it matches the structure of the ycb dataset. While running python3 -m datasets.ycb.preprocess_testset or python3 -m datasets.ycb.ycb_dataset I always get an error with 'NoneType' class or object.

Do you have an idea what is wrong ?
<img width="682" alt="errorpvn3d" src="https://user-images.githubusercontent.com/60901212/91647803-41813180-ea5f-11ea-8df3-896f6a3338aa.png">

**Comment by ethnhe** [comment]
It seems that there are something wrong in  ```def get_item(self, item_name)``` in ```ycb_dataset.py```, try to remove the first ```try: except``` to see which line of code cause the except.

**Comment by Ixion46** [comment]
Okay thanks, i will try :)
