### ISSUE TITLE
使用PyPCL替换PythonPCL

### ISSUE THREAD

**Issue by JarintotionDin** [ethnhe/PVN3D#45]
朋友你好~我想使用PyPCL替换PythonPCL，以便在conda环境下运行pvn3d。但是我不清楚YcbDataset以及LineModDateset中get_normal()的作用。能否请教你解答一下，我好改成PyPCL版本。

**Comment by ethnhe** [comment]
get_normal()通过传进去的点云获得每个点的法向量。
