### ISSUE TITLE
how to adjust arguments to fill depth map better?

### ISSUE THREAD

**Issue by MengHao666** [ethnhe/PVN3D#46]
Hi,
   First, thanks for such great work!
   I have some confusions about depth map filling process.
   [Here](https://github.com/ethnhe/PVN3D/blob/5878f05da7cd7697e2ab6bc8c20822bf792b662f/pvn3d/lib/utils/ip_basic/depth_map_utils.py#L133),you have lots of arguments or constant parameters?
   Could u tell me how u adjust them in this work? Could u give me some inferences?Ijust want to modify these params. but don't know how to.

**Comment by ethnhe** [comment]
You can first read the [papar](https://arxiv.org/abs/1802.00036) and learn how the algorithm work and then adjust the algorithm. We simply adjust the parameters according to the maximum depth in the depth image. In fact, the algorithm is designed for outdoor scenes and can not fit very well for indoor scenes.
