### ISSUE TITLE
Training other datasets with pvn3d

### ISSUE THREAD

**Issue by BenjaminBo** [ethnhe/PVN3D#48]
Hi,
I would like to train other datasets using pvn3d. 
The datasets are given here https://bop.felk.cvut.cz/datasets/. 
As a first step I would like to train the "tless" dataset.
I'm not quite sure yet, how I would go about doing that.
 
Could somebody help me understand how I would have to change the format of the tless dataset or how and where I would have to adjust the code so that training on the tless dataset would be possible?

**Comment by BenjaminBo** [comment]
@ethnhe

**Comment by ethnhe** [comment]
You can revise the data preprocess script ```dataets/ycb/ycb_dataset.py``` or ```datasets/linemod/linemod_dataset.py``` to fit tless dataset. Also, you may need to revise some variables in ```common.py```

**Comment by ethnhe** [comment]
The guide for adaptation to new datasets has been added in [README](https://github.com/ethnhe/PVN3D#adaptation-to-new-dataset).

**Comment by engqing** [comment]
@BenjaminBo Have you solved the problem yet?
