### ISSUE TITLE
conda 環境執行PVN3D

### ISSUE THREAD

**Issue by redredraccoon** [ethnhe/PVN3D#50]
Installation中的其餘套件都安裝成功，
一直嘗試安裝python-pcl，但還是無法成功，以致執行PVN3D後得到下圖的error message: 
![image](https://user-images.githubusercontent.com/38128523/95039216-bdc40000-0702-11eb-8bcc-31aadc4abc03.png)
想請問有其他可以代替python-pcl的package嗎?

**Comment by ethnhe** [comment]
python-pcl 只是用在数据预处理时计算点云的法向量，在```datasets/ycb/ycb_dataset.py```和```datasets/linemod/linemod_dataset.py```中、你可以找找别的算法向量的方法替代。也可以直接去掉——点云输入不加法向量也可以，不过模型的输入（PointNet++分支)需要做点相对应的小修改。

**Comment by ethnhe** [comment]
You can try the algorithm in this [repo](https://github.com/hfutcgncas/normalSpeed), which is easy to install and run.
