### ISSUE TITLE
Why big loss?

### ISSUE THREAD

**Issue by Ixion46** [ethnhe/PVN3D#53]
Hey @ethnhe I hope you can help me again.
I have created my own dataset in the structure of ycb and started to train it. My depth images are created in NDDS and are in cm, so i took factor_depth = 100, is this correct?
What can be another reason of this high loss and what would be a "good" result?
![loss](https://user-images.githubusercontent.com/60901212/96368282-718dac80-1153-11eb-89bc-d871d035d022.png)

**Comment by ethnhe** [comment]
Check that the final output point cloud in your dataset scripts is in m.  Visualize and check that your train and validate set is correct by running your dataset scripts, for example, ```python3 -m datasets.ycb.ycb_dataset``` for YCB-Video dataset.

**Comment by ethnhe** [comment]
The guide for adaptation to new datasets has been added in [README](https://github.com/ethnhe/PVN3D#adaptation-to-new-dataset).
