### ISSUE TITLE
How to train create our own dataset?

### ISSUE THREAD

**Issue by LCJHust** [ethnhe/PVN3D#54]
Hi:
    I want to train the pvn3d with my own datasets, then I create dataset like YCB-Video-Dataset, but I have no idea how to get  [radius.txt](https://github.com/ethnhe/PVN3D/blob/master/pvn3d/datasets/ycb/dataset_config/radius.txt). So how I can compute the radius of any other objects?

**Comment by ethnhe** [comment]
We obtained object info following [PVNet](https://github.com/zju3dv/pvnet/blob/master/lib/utils/data_utils.py):
The corners.txt is the bounding box corners. It can be obtained by getting the min_x, max_x, min_y, max_y ... of all mesh points.
The radius can be obtained by half the diagonal distance of the 3D bounding box.
The farthest.txt contains keypoint selected from all mesh points with the Farthest Point Sampling (FPS) algorithm.

**Comment by LCJHust** [comment]
Thank you for your reply! However, I have calculated half the diagonal distance of the 3D bounding box which can't corresponding to radius.txt. So, Is there something wrong?

**Comment by ethnhe** [comment]
Did you use scripts from [PVNet](https://github.com/zju3dv/pvnet/blob/master/lib/utils/data_utils.py), the radius.txt is generated from that scripts.

**Comment by ethnhe** [comment]
Code for generating info (eg. keypoint and corner point) of new objects has been added. And the guide for adaptation to new datasets has been added in [README](https://github.com/ethnhe/PVN3D#adaptation-to-new-dataset).
