### ISSUE TITLE
Issue running demo.py for testing on pre-trained YCB weights

### ISSUE THREAD

**Issue by kaushikbalasundar** [ethnhe/PVN3D#56]
I am trying to run the demo for YCB dataset with the pre-trained weights. I have followed everything on the README.md, and did not encounter any issues, until this. What might be the issue?

![issue_PVN3d](https://user-images.githubusercontent.com/44526371/101291169-c208b880-382c-11eb-9ec6-142e15fb1784.png)

**Comment by ethnhe** [comment]
It seems that your dataprovider in ```datasets/ycb/ycb_dataset.py``` returns some NoneType data, check that you set your dataset info in ```common.py``` properly and run ```python3 -m datasets.ycb.ycb_dataset``` to see if the data provider returns correct types of data.

**Comment by richard-qian** [comment]
Hi, I've met the exact same issue. I ran the `datasets.ycb.ycb_dataset` and it still returned 'NoneType' error. I guess it might caused by PCL and python-pcl version issue, but I haven't solved it yet. Have you solved it? Can you kindly share what you did? @kaushikbalasundar
