### ISSUE TITLE
Hello! I have a question, where is the part of the voting?

### ISSUE THREAD

**Issue by aiai84** [ethnhe/PVN3D#59]
Thank you for uploading your work? I tested your model and it worked well. However, I had not find the hough voting part. Is there some one can help me to figure it out? Thank you very much!

**Comment by ethnhe** [comment]
The voting function to obtained voted keypoints and the center point is defined [here](https://github.com/ethnhe/PVN3D/blob/ccc84ba772c9e44ee66505046c8e15ffdf3314b5/pvn3d/lib/utils/pvn3d_eval_utils.py#L37),
 and the voting procedure (Meanshift clustering) is called [here](https://github.com/ethnhe/PVN3D/blob/ccc84ba772c9e44ee66505046c8e15ffdf3314b5/pvn3d/lib/utils/pvn3d_eval_utils.py#L97).
