### ISSUE TITLE
Adaptation to custom dataset

### ISSUE THREAD

**Issue by luigifaticoso** [ethnhe/PVN3D#64]
Hello, I'm trying to train the model on my custom dataset. 
I have created my synthetic dataset as similar as possible to the Linemod_preprocessed. 
### **My steps:**
- Created a folder in datasets copied from linemod folder.
- Modified the folder obj_kps putting the output generated by ` python3 gen_obj_info.py --help`, the generated files only had `center.txt`, `corners.txt`, `farthest.txt` and `radius.txt`. It is not similar to the linemod dataset with `farthest4.txt`, `farthest12.txt` etc. - **First question:** How do I generate the other farthest missing files similar to linemod?
- I have changed the `dataset_config/models_info.yml` based on my measures obtained in the previous step
- I have modified the `mydataset_dataset.py` changing the width and height of my images, changing the references to linemod and pointing them to the config file of my new dataset
- Changed the `preprocess_testset` based on my needs
- in file `common.py` I have added my new dataset adding this part (doing copy and paste of linemod) :
```python
        elif self.dataset_name == 'blm':
            self.n_objects = 1 + 1
            self.n_classes = 1 + 1
            self.blm_cls_lst = [
                1
            ]
            self.blm_obj_dict={
                'blm':1,
            }
            self.blm_id2obj_dict = dict(
                zip(self.blm_obj_dict.values(), self.blm_obj_dict.keys())
            )
            self.blm_root = os.path.abspath(
                os.path.join(self.exp_dir, 'datasets/blm/')
            )
            self.blm_kps_dir = os.path.abspath(
                os.path.join(self.exp_dir, 'datasets/blm/blm_obj_kps/')
            )
            self.val_test_pkl_p = os.path.join(
                self.exp_dir, 'datasets/blm/test_val_data.pkl',
            )
            prep_fd = os.path.join(
                self.blm_root, "preprocess_testset"
            )
            ensure_fd(prep_fd)
            self.preprocessed_testset_ptn = os.path.abspath(
                os.path.join(prep_fd, '{}_pp_vts.pkl')
            )
            self.preprocessed_testset_pth = self.preprocessed_testset_ptn.format(cls_type)
            self.use_preprocess = False

            blm_r_pth = os.path.join(self.blm_root, "dataset_config/models_info.yml")
            blm_r_file = open(os.path.join(blm_r_pth), "r")
            self.blm_r_lst = yaml.load(blm_r_file)

            self.val_nid_ptn = "/data/6D_Pose_Data/datasets/BLM/pose_nori_lists/{}_real_val.nori.list"

``` 

- I have added the intrinsic Matrix of my camera to the `common.py.`

Regarding my dataset, I have generated the images and labels using BlenderProc; I have the `gt.yml`, `info.yml` and everything except for the Masks. - **Second question:** Do I need to generate the masks or is it generated in some process inside? could that be the problem?

I have modified those necessary files here documented, but I still need to change some parts.
This is the current output:
```shell
python3 -m train.train_blm_pvn3d --cls blm
/home/pytorch/PVN3D/pvn3d/common.py:173: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.blm_r_lst = yaml.load(blm_r_file)
/home/pytorch/PVN3D/pvn3d/common.py:134: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.lm_r_lst = yaml.load(lm_r_file)
/home/pytorch/PVN3D/pvn3d/common.py:173: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.blm_r_lst = yaml.load(blm_r_file)
cls_type:  blm
cls_id in blm_dataset.py 1
/home/pytorch/PVN3D/pvn3d/datasets/blm/blm_dataset.py:41: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.meta_lst = yaml.load(meta_file)
Train without rendered data from https://github.com/ethnhe/raster_triangle
Train without fuse data from https://github.com/ethnhe/raster_triangle
train_dataset_size:  10
cls_id in blm_dataset.py 1
val_dataset_size:  15
loading pretrained mdl.
/usr/local/lib/python3.7/dist-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
{'bn_decay': 0.5,
 'bn_momentum': 0.9,
 'cal_metrics': False,
 'checkpoint': None,
 'cls': 'blm',
 'decay_step': 200000.0,
 'epochs': 1000,
 'eval_net': False,
 'lr': 0.01,
 'lr_decay': 0.5,
 'run_name': 'sem_seg_run_1',
 'test': False,
 'test_occ': False,
 'weight_decay': 0}
epochs:   0%|                                                                                                                                      | 0/25 [00:00<?, ?it/s]
train:   0%|                                                                                                                                     | 0/5000 [00:00<?, ?it/s]
```
How can I have more output and understand where it's wrong?

**Comment by ethnhe** [comment]
Hi, 
- For your first question, the default setting is to generate 8 keypoints for each object, which is the best setting in our experiments, and we think you do not need to get other numbers of keypoint like the LineMOD dataset, which we generate for ablation study in our paper. If you want to get them, you can modify the code [here](https://github.com/ethnhe/PVN3D/blob/bb683b7d88b0ec75a6e58d9667509a5926aeeb06/pvn3d/lib/utils/dataset_tools/gen_obj_info.py#L102), by changing the ```num=8``` to the number you want and also the name of the saving file.
- For your second question, yes, you need to provide the masks of target objects because our model needs to train the instance semantic segmentation branch. If you train your model for a single class of objects, you can follow the setting of LineMOD and set 1 as target objects and 0 as background in your mask. If you don't know how to generate the mask of an object with BlenderProc, you can also try our [raster_triangle](https://github.com/ethnhe/raster_triangle) to generate it with object ply model, gt object pose, and camera intrinsic setting. 
- After these settings are finished, run the dataset provider scripts, ```mydataset_dataset.py``` in your case to visualize the data and check if all the scripts run correctly.

**Comment by luigifaticoso** [comment]
Ok Perfect,
thank you a lot for your message. 
I have managed to generate the 8 keypoints, I will maybe try different settings later.
I have managed to generate the binary mask in Blender Proc, but I'm planning to ampliate the dataset using your solution raster_triangle.

I have managed to go forward, there was an issue in `mydataset_dataset.py` at the meta part by printing it out I have just commented and it goes forward.

```python
                # else:
                #     meta = meta[0]
                #     print("meta: ",meta)
```
The next issue I'm trying to understand is this part where it expects 11 elements from `cu_dt` but it gets 13 instead.
Below is my cu_dt file, I'm trying to understand right now what is the issue here. If you happen to understand it on the spot, it would be great, I'm trying to understand from code step by step going backward.

`ValueError: too many values to unpack (expected 11)
`
```python
[tensor([[[[123., 119., 114.,  ...,  26.,  20.,  14.],
          [112., 120., 117.,  ...,  38.,  43.,  34.],
          [111., 115., 118.,  ...,  42.,  43.,  40.],
          ...,
          [ 68.,  69.,  68.,  ...,   9.,  11.,  13.],
          [ 61.,  65.,  64.,  ...,   9.,  13.,  10.],
          [ 67.,  56.,  64.,  ...,   9.,  13.,  10.]],

         [[112., 112., 107.,  ...,  15.,  15.,  12.],
          [107., 112., 111.,  ...,  24.,  29.,  26.],
          [100., 107., 109.,  ...,  29.,  28.,  26.],
          ...,
          [ 87.,  89.,  85.,  ...,   2.,   2.,   6.],
          [ 78.,  84.,  81.,  ...,   2.,   4.,   5.],
          [ 81.,  70.,  82.,  ...,   2.,   6.,   7.]],

         [[100.,  91.,  87.,  ...,   0.,   0.,   0.],
          [ 88.,  91.,  91.,  ...,   0.,   0.,   0.],
          [ 88.,  90.,  91.,  ...,   0.,   0.,   0.],
          ...,
          [130., 132., 128.,  ...,   0.,   0.,   0.],
          [120., 128., 123.,  ...,   0.,   0.,   0.],
          [115., 108., 120.,  ...,   0.,   0.,   0.]]],


        [[[ 83.,  80.,  75.,  ..., 185., 183., 182.],
          [ 75.,  73.,  73.,  ..., 188., 186., 186.],
          [ 72.,  72.,  77.,  ..., 191., 193., 194.],
          ...,
          [106., 106., 107.,  ..., 107., 107., 106.],
          [104., 109., 105.,  ..., 106., 110., 105.],
          [ 95., 104., 102.,  ..., 107., 111., 108.]],

         [[ 82.,  80.,  77.,  ..., 174., 173., 171.],
          [ 78.,  75.,  75.,  ..., 178., 174., 174.],
          [ 76.,  74.,  76.,  ..., 180., 181., 184.],
          ...,
          [ 99.,  99., 100.,  ...,  90.,  91.,  87.],
          [ 98., 100.,  98.,  ...,  89.,  92.,  86.],
          [ 93.,  94.,  96.,  ...,  93.,  91.,  92.]],

         [[ 79.,  77.,  78.,  ..., 172., 166., 174.],
          [ 74.,  75.,  77.,  ..., 172., 168., 168.],
          [ 76.,  75.,  77.,  ..., 175., 179., 180.],
          ...,
          [ 96.,  97.,  98.,  ...,  84.,  84.,  82.],
          [ 95.,  97.,  96.,  ...,  86.,  85.,  82.],
          [ 90.,  93.,  96.,  ...,  86.,  87.,  88.]]]], device='cuda:0'), tensor([[[-10.9882, -11.1630,  31.0690],
         [-10.8246, -11.1745,  31.1010],
         [ -8.9203, -11.2550,  31.3250],
         ...,
         [  3.7647,   4.2656,  11.8720],
         [  3.8816,   4.1409,  11.5250],
         [  3.9220,   4.0985,  11.4070]],

        [[ -4.7845,  -5.1042,  14.2060],
         [ -4.6498,  -5.1541,  14.3450],
         [-10.9887, -16.7619,  46.6520],
         ...,
         [  5.2613,  11.6387,  32.3930],
         [  6.9285,  11.9207,  33.1780],
         [  8.9516,  12.2635,  34.1320]]], device='cuda:0'), tensor([[[-1.0988e+01, -1.1163e+01,  3.1069e+01,  ...,  1.0765e-01,
           8.7787e-01, -4.6664e-01],
         [-1.0825e+01, -1.1174e+01,  3.1101e+01,  ...,  1.0488e-01,
           8.7809e-01, -4.6686e-01],
         [-8.9203e+00, -1.1255e+01,  3.1325e+01,  ...,  4.3519e-02,
           8.6359e-01, -5.0231e-01],
         ...,
         [ 3.7647e+00,  4.2656e+00,  1.1872e+01,  ..., -1.1670e-01,
          -9.6928e-01,  2.1652e-01],
         [ 3.8816e+00,  4.1409e+00,  1.1525e+01,  ..., -2.5816e-01,
          -9.5580e-01,  1.4073e-01],
         [ 3.9220e+00,  4.0985e+00,  1.1407e+01,  ..., -2.5743e-01,
          -9.5657e-01,  1.3677e-01]],

        [[-4.7845e+00, -5.1042e+00,  1.4206e+01,  ...,  7.2914e-01,
           3.6436e-01, -5.7931e-01],
         [-4.6498e+00, -5.1541e+00,  1.4345e+01,  ...,  7.6976e-01,
           3.4169e-01, -5.3918e-01],
         [-1.0989e+01, -1.6762e+01,  4.6652e+01,  ...,  7.9819e-01,
           5.9784e-01, -7.3994e-02],
         ...,
         [ 5.2613e+00,  1.1639e+01,  3.2393e+01,  ...,  2.8122e-01,
          -9.2213e-01, -2.6568e-01],
         [ 6.9285e+00,  1.1921e+01,  3.3178e+01,  ...,  2.8115e-01,
          -9.2268e-01, -2.6387e-01],
         [ 8.9516e+00,  1.2264e+01,  3.4132e+01,  ...,  2.8119e-01,
          -9.2248e-01, -2.6452e-01]]], device='cuda:0'), tensor([[[     4,      8,     53,  ..., 262113, 262127, 262132]],

        [[    16,     25,     88,  ..., 262003, 262036, 262074]]],
       device='cuda:0'), tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]], device='cuda:0'), tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0'), tensor([[[1],
         [0]],

        [[1],
         [0]]], device='cuda:0'), tensor([[[[ -0.6551,  -0.5228,  -0.5454,  16.1685],
          [  0.3003,  -0.8426,   0.4469, -12.2521],
          [ -0.6932,   0.1290,   0.7091, -19.3717]],

         [[  0.0000,   0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000,   0.0000]]],


        [[[  0.9305,   0.2812,  -0.2346,   6.4810],
          [  0.3295,  -0.9223,   0.2018,  -5.1266],
          [ -0.1596,  -0.2651,  -0.9509,  30.7622]],

         [[  0.0000,   0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000,   0.0000]]]], device='cuda:0'), tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0'), tensor([[[[ 16.0277, -12.5376, -19.3601],
          [ 16.2932, -11.9937, -19.3775],
          [ 16.1769, -12.2156, -19.4195],
          [ 16.2347, -12.0989, -19.4304],
          [ 15.9963, -12.4754, -19.3035],
          [ 16.3418, -12.0355, -19.4383],
          [ 16.1854, -12.1432, -19.3961],
          [ 16.2682, -12.0313, -19.4342]],

         [[  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000]]],


        [[[  6.5782,  -5.4269,  30.7193],
          [  6.3909,  -4.8563,  30.7963],
          [  6.5104,  -5.0804,  30.7881],
          [  6.4753,  -4.9563,  30.8095],
          [  6.5502,  -5.3833,  30.6461],
          [  6.4101,  -4.8767,  30.8801],
          [  6.4824,  -5.0138,  30.7625],
          [  6.4529,  -4.8849,  30.8204]],

         [[  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000],
          [  0.0000,   0.0000,   0.0000]]]], device='cuda:0'), tensor([[[ 16.1606, -12.2661, -19.3690],
         [  0.0000,   0.0000,   0.0000]],

        [[  6.4847,  -5.1420,  30.7581],
         [  0.0000,   0.0000,   0.0000]]], device='cuda:0'), tensor([[[711.1113,   0.0000, 255.5000],
         [  0.0000, 711.1113, 255.5000],
         [  0.0000,   0.0000,   1.0000]],

        [[711.1113,   0.0000, 255.5000],
         [  0.0000, 711.1113, 255.5000],
         [  0.0000,   0.0000,   1.0000]]], device='cuda:0'), tensor([1000., 1000.], device='cuda:0')]

```

**Comment by ethnhe** [comment]
The DEBUG setting return more information for visualization of preprocessed data in the dataset.py, [LineMOD](https://github.com/ethnhe/PVN3D/blob/bb683b7d88b0ec75a6e58d9667509a5926aeeb06/pvn3d/datasets/linemod/linemod_dataset.py#L367) for example. And it's highly recommended to visualize and check if the data are processed properly by visualizing them with ```python3 -m datasets.linemod.linemod_dataset```. Which gives the picture as follows:
![linemod_vis_data](https://user-images.githubusercontent.com/44842139/108049426-352b7800-7083-11eb-8c77-adbaa3b6758f.PNG)
So you can check the center point (blue point) and keypoints (red points) are labeled correctly.

**Comment by luigifaticoso** [comment]
Thank you for helping,
I'm trying to debug the labels because they are not correct.
I'm trying to find If I have homogenous model data to the linemod dataset. 
I have tried to use ```python3 gen_obj_info.py``` on the ape model provided by linemod, but doesn't seem to have the same numbers of the original.
I have scaled down the ply model to m ( so to have homogenous results )  and use the gen_obj_info and this is the output ( on the right ) compared with the one provided by linemod dataset :
![Screenshot from 2021-02-16 15-18-07](https://user-images.githubusercontent.com/16363592/108075048-313f2c00-706a-11eb-80c9-03612b958e9d.png)
My labels are wrong, I am going to share the output of  `python3 -m datasets.linemod.linemod_dataset`
This is by scaling the model to m:

![train_0_rgb](https://user-images.githubusercontent.com/16363592/108075573-d0642380-706a-11eb-8fe4-081cfadad223.png)

instead scaled to mm it's totally out of the image

**Comment by ethnhe** [comment]
The keypoints **are in m** and are generated by the FPS algorithm with random initialization. The selected points may be different but that won't affect the performance much.  For your case, if the generated keypoints of your model are in m, you should check that your GT poses are in ['cv' coordinate system](https://github.com/zju3dv/pvnet-rendering/blob/7c36dfa5575dbb587fe766a88bb5dd1e517d725c/blender/blender_utils.py#L43), rather than default poses from Blender.

**Comment by luigifaticoso** [comment]
Thank you for your message, I started debugging piece by piece and managed to arrive at this point, where the center point is ok but the others are not. Where can I investigate more in this case? I have printed out the points from white ( farthest ) to black ( nearest ) points and this happens.

![4_rgb](https://user-images.githubusercontent.com/16363592/108347465-cfed9900-71e0-11eb-9667-8f50d4f9651a.png)

![2_rgb](https://user-images.githubusercontent.com/16363592/108347548-ed226780-71e0-11eb-8863-011cd20b6d16.png)

I have checked my model.ply and doesn't seem to have any problem. Any help to things I could check out could be really helpful!
thank you

**Comment by ethnhe** [comment]
It seems like the left-hand coordinate system and right-hand-coordinate system issue. We use the right-hand coordinate system and it seems like your model is in the left-hand coordinate system. Try to flip the y-axis of each vertex and keypoint of the object in the object coordinate system.

**Comment by ethnhe** [comment]
It seems like the left-hand coordinate system and right-hand-coordinate system issue. We use the right-hand coordinate system and it seems like your model is in the left-hand coordinate system. Try to flip the y-axis of each vertex and keypoint of the object in the object coordinate system.

**Comment by luigifaticoso** [comment]
Thank you a lot for helping me although it is not an issue regarding your work primarily @ethnhe.

I just tried moving around the coordinates, but it doesn't solve my problem. 
```python
for kp3dvar in range(len(kp3d)):
                    kp3d[kp3dvar][1] = -kp3d[kp3dvar][1]
```
I'm checking the code that has generated the translation and rotation matrix.
Here below, I attach some pictures with the axis flipped so that maybe you have more experience than me, and it could be easier to understand where the problem could be. 
Thank you a lot,

this is the original
![no_flip](https://user-images.githubusercontent.com/16363592/108718666-fa13c380-751e-11eb-8a7a-a611bc1fcea5.png)
this is with the x keypoints flipped
![x_flipped](https://user-images.githubusercontent.com/16363592/108718669-faac5a00-751e-11eb-9adb-488ea6ef3e52.png)
this is with the y keypoints flipped
![y_flipped](https://user-images.githubusercontent.com/16363592/108718670-faac5a00-751e-11eb-8299-f9ad4de09ae8.png)

**Comment by qingweihk** [comment]
> generate

Hi,luigifaticoso,May I ask how did you get gt.yml amd info.yml? Cause
When I want to try it on custom datasets(generated following pvnet instructions:
I have got :

rgb
depth
labels
transforms
centers.txt
farthest.txt
intrinsics.json
part.ply
radius.txt
transforms.npy

But how to get models_info.yml and gt.yml for custom datasets?
Thanks very much

**Comment by Ultraopxt** [comment]
> **are in m** and are generated by the FPS algorithm with random initialization. The selected points may be different but that won't affect the performance much. For your case, if the generated keypoints of your model are in m, you should check that your GT poses are in ['cv' coordinate system](https://github.com/zju3dv/pvnet-rendering/blob/7c36dfa5575dbb587fe766a88bb5dd1e517d725c/blender/blender_utils.py#L43), rather than default poses from Blender.

May I ask original linemod model.ply and keypoints generated form FPS are in mm or in m? Cause my keypoints generated from  FPS are inaccurate.

**Comment by ethnhe** [comment]
The vertexes in the model.ply are all converted to be in m, and the keypoints selected from them with FPS are also in m.

**Comment by Ultraopxt** [comment]
> The vertexes in the model.ply are all converted to be in m, and the keypoints selected from them with FPS are also in m.

Thanks very much!
I visualize my datasets,and keypoints and center point are as followings:
![test_rgb (6)](https://user-images.githubusercontent.com/48346200/125546400-fadfabb7-20a5-4044-98f0-c92b2e090ff8.jpg)
![test_rgb (5)](https://user-images.githubusercontent.com/48346200/125546403-23dfd24f-2963-42b8-96a8-bc7a89091155.jpg)
![test_rgb (4)](https://user-images.githubusercontent.com/48346200/125546405-6381b13b-9911-45c8-9d65-a4df29a54919.jpg)

May I ask how can I slove the  position deviation of keypoints and center point?

**Comment by ethnhe** [comment]
Not very sure, but it seems that maybe the ground truth pose transforming the object from the object coordinate system to the camera coordinate system is not calculated properly. Also, check that the object coordinate system and the camera coordinate system are all right-hand coordinate systems. You can also transform the mesh vertexes to the camera coordinate system and project them to the image to check the pose parameters.

**Comment by Ultraopxt** [comment]
> Not very sure, but it seems that maybe the ground truth pose transforming the object from the object coordinate system to the camera coordinate system is not calculated properly. Also, check that the object coordinate system and the camera coordinate system are all right-hand coordinate systems. You can also transform the mesh vertexes to the camera coordinate system and project them to the image to check the pose parameters.

Thanks very much!

**Comment by andreazuna89** [comment]
@luigifaticoso can you write here how can you generate gt.yml and info.yml for a custom dataset?

Thanks
