### ISSUE TITLE
Pretrained models unavailable without registration

### ISSUE THREAD

**Issue by Kppeppas** [ethnhe/PVN3D#65]
Hello,

I'm trying to download the models from the provided links, but the onedrive one is down. The baidu one is up, but I cannot register as my mobile number is not accepted. Is it possible to share an alternative link?

**Comment by ethnhe** [comment]
Hi, I check the one drive links and they work well. You can check that you can access the one drive webpage and try them again.

**Comment by Kppeppas** [comment]
Thanks for your reply. I've just tried from a different PC and browser and it works fine. It was failing from Firefox and working in Chrome in case it happens to anyone else. Thanks again and closing.
