### ISSUE TITLE
No such file renders/{}/file_list.txt

### ISSUE THREAD

**Issue by luigifaticoso** [ethnhe/PVN3D#66]
Hello, 
I finally managed to orientate better my dataset and now I want to start training. The train stops here:
```python
rnd_img_pth = os.path.join(
                self.root, "renders/{}/file_list.txt".format(cls_type)
            )
```
It says it cannot find the /renders/{}/file_list.txt between my files. I don't know what it is and I don't know what is the renders folder. I am trying to investigate more. It's safe to put it in a try except or is it needed?
The same things goes for linemod dataset

**Comment by luigifaticoso** [comment]
I see, they come from [raster_triangle](https://github.com/ethnhe/raster_triangle).

**Comment by soonwoojung** [comment]
I'm getting same error but i don't know how to fix it.

i'm using colab now and got error message =
```
FileNotFoundError: [Errno 2] No such file or directory: '/content/PVN3D/pvn3d/datasets/linemod/Linemod_preprocessed/renders/ape/file_list.txt'
```

I can't understand how to fix this error with " raster_triangle " github.

 I'm exactly same that :  I don't know what it is and I don't know what is the renders folder, and how to fix it

**Comment by ethnhe** [comment]
Follow the README in raster_triangle  and generate the render and fuse data. The generated data will be in the ```Linemod_preprocessed/renders``` and ```Linemod_prepocessed/fuse``` respectively.
