### ISSUE TITLE
Error about 'neupeak'

### ISSUE THREAD

**Issue by EasonEdison** [ethnhe/PVN3D#7]
I install all requirement.txt and try```pip isntall neupeak```ande```conda install neupeak```, but both not work, how can I do to instll it ?

**Comment by ethnhe** [comment]
Install cv2 by ```pip3 install opencv-python```. Then revise the line of code ```from neupeak.utils.webcv2 import imshow, waitKey``` to ```from cv2 import imshow, waitKey```. 
The code is updated, you can also use ```git pull``` to update the code.

**Comment by EasonEdison** [comment]
OK，it work！
