### ISSUE TITLE
A question about code, please help!

### ISSUE THREAD

**Issue by 74284853** [ethnhe/PVN3D#73]
I recently tried to run your code, encountered a problem, I hope I can get your help, can your code output the six dimensional coordinates of the key point or the center point of the forecast target??

**Comment by 74284853** [comment]
I used the linemod dataset.

**Comment by ethnhe** [comment]
What're the six-dimensional coordinates mean? You can print the 3-dimensional coordinate in the camera coordinate system in the data preprocessing scripts: [center point](https://github.com/ethnhe/PVN3D/blob/82ec7186e990a2f86b376fdcaa6d3e40cfb56d3f/pvn3d/datasets/linemod/linemod_dataset.py#L287), [keypoints](https://github.com/ethnhe/PVN3D/blob/82ec7186e990a2f86b376fdcaa6d3e40cfb56d3f/pvn3d/datasets/linemod/linemod_dataset.py#L303).

**Comment by 74284853** [comment]
> What're the six-dimensional coordinates mean? You can print the 3-dimensional coordinate in the camera coordinate system in the data preprocessing scripts: [center point](https://github.com/ethnhe/PVN3D/blob/82ec7186e990a2f86b376fdcaa6d3e40cfb56d3f/pvn3d/datasets/linemod/linemod_dataset.py#L287), [keypoints](https://github.com/ethnhe/PVN3D/blob/82ec7186e990a2f86b376fdcaa6d3e40cfb56d3f/pvn3d/datasets/linemod/linemod_dataset.py#L303).

Shouldn't the result predicted by the code include the translation coordinate T and rotation coordinate R of the object?

**Comment by 74284853** [comment]
For example, can I use your code to detect the actual coordinates of objects on the desktop, including translation coordinates (x, y, z) and rotation coordinates (Rx, Ry, Rz)?

**Comment by ethnhe** [comment]
We output the transform matrix that can transform the object from its object coordinate system to the camera coordinate system, they are at ```lib/utils/pvn3d_eval_utils.py```([link](https://github.com/ethnhe/PVN3D/blob/82ec7186e990a2f86b376fdcaa6d3e40cfb56d3f/pvn3d/lib/utils/pvn3d_eval_utils.py#L196).

**Comment by 74284853** [comment]
Thank&nbsp;you&nbsp;very&nbsp;much&nbsp;for&nbsp;your&nbsp;help！！
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2021年3月22日(星期一)&nbsp;凌晨0:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:Re:&nbsp;[ethnhe/PVN3D]&nbsp;A&nbsp;question&nbsp;about&nbsp;code,&nbsp;please&nbsp;help!&nbsp;(#73)



 
We output the transform matrix that can transform the object from its object coordinate system to the camera coordinate system, they are at lib/utils/pvn3d_eval_utils.py(link.
 
&mdash;
