### ISSUE TITLE
Resume Training

### ISSUE THREAD

**Issue by luigifaticoso** [ethnhe/PVN3D#75]
Hello, 
I have a question about the resume of the training. 
When I try to load a checkpoint it evaluates every 200 iterations for 15 epochs. Is it meant to be like this when resuming training from the checkpoint? Or the loading of the model is meant only for evaluation purpose? 

I am investigating, if I find an answer I will write it here
Thank you

**Comment by ethnhe** [comment]
Yes, it can resume training from the checkpoint from the iter last stop. Specifically, the number of training iteration is also loaded when resuming [here](https://github.com/ethnhe/PVN3D/blob/b8cd1d8996ee25f1bc357c023ff9fb202e07c438/pvn3d/train/train_ycb_pvn3d.py#L465), which is bigger than ```800*100``` and satisfies [this condition](https://github.com/ethnhe/PVN3D/blob/b8cd1d8996ee25f1bc357c023ff9fb202e07c438/pvn3d/train/train_ycb_pvn3d.py#L330) to evaluates every 200 iterations, if you load our pre-trained model.
