### ISSUE TITLE
A Small Bug in common.py

### ISSUE THREAD

**Issue by Jameschen7** [ethnhe/PVN3D#76]
Hi,

I would like to point out a small bug in common.py that line 118 wrongly overwrites the list of linemod symmetric class ids which is correctly defined in line 93. This error will just lead to incorrect selection of add(-s) auc during evaluation, but the add auc and adds auc themselves are unaffected.

Anyway, thanks for sharing your code!

**Comment by ethnhe** [comment]
Thanks for pointing it out and it has been fixed.
