### ISSUE TITLE
how to get models_info.yml  and gt.yml for custom dataset?

### ISSUE THREAD

**Issue by Ultraopxt** [ethnhe/PVN3D#83]
Thanks for your great job.
When I want to try it on custom datasets(generated following pvnet instructions:
I have got :

- rgb
- depth
- labels
- transforms
- centers.txt
- farthest.txt
- intrinsics.json
- part.ply
- radius.txt
- transforms.npy

But how to get models_info.yml and gt.yml for custom datasets? 
Thanks very much

**Comment by Jakob0330** [comment]
Hello, did you solve this problem? Is it possible for you to share the method if you have already solved it?
