### ISSUE TITLE
How to build with CUDA11+?

### ISSUE THREAD

**Issue by Ultraopxt** [ethnhe/PVN3D#84]
May I ask How to build with CUDA11+?
Cause my GPU is 30 series

**Comment by LEONHWH** [comment]
Hi,您好。请问你用30系列的显卡能通过成功实现”python3 setup.py build_ext“的步骤吗？
CUDA11+以上需要配置pytorch==1.7以上，我想知道是否能通过修改部分代码或者更换一些配置版本来成功跑通代码？
期待您的回复，谢谢！

**Comment by LEONHWH** [comment]
> 请问如何用CUDA11+构建？ 因为我的 GPU 是 30 系列

你好，你好吗？你用30系列的显卡能通过成功实现“python3 setup.py build_ext”的步骤
CUDA11+以上需要配置pytorch==1.7以上，我想是否能通过部分代码修改或者更换一些配置版本来成功跑通代码？
期待您的回复，谢谢！

**Comment by HannahHaensen** [comment]
@LEONHWH  or @qingweihk did you find a solution to compile it with Cuda 11 and pytorch 1.8 or higher?
