### ISSUE TITLE
No keypoints on my custom datasets

### ISSUE THREAD

**Issue by Ultraopxt** [ethnhe/PVN3D#85]
Thanks for your great job.
I try to Visualize and check do I  process the data properly, the results are as following: only have center points without keypoints.Is there something wrong? Many thanks!
![test_rgb (3)](https://user-images.githubusercontent.com/48346200/123240205-af2cab80-d512-11eb-85e8-f273d124c29d.jpg)
![test_rgb](https://user-images.githubusercontent.com/48346200/123240208-b05dd880-d512-11eb-9fb8-b738ca1b6b0a.jpg)
![nrm_map](https://user-images.githubusercontent.com/48346200/123240209-b0f66f00-d512-11eb-9d6a-d688d4fc9de5.jpg)

**Comment by lululovecode** [comment]
我也遇到了相同的问题，请问您解决了吗？是怎么解决的？求！谢谢！
