### ISSUE TITLE
Keypoints are inaccurate  

### ISSUE THREAD

**Issue by Ultraopxt** [ethnhe/PVN3D#86]
I use your code to generate some infomation like farest points of my custom dataset ,
and then try to Visualize and check the key points and center .The results are as following: 

-  center points looks right
- but keypoints are inaccurate,some of them(red points) are on the boundry of  the pictures .

And I have printed keypoints' coordinate values: some of them are as big as more than 5000.
I have tried twice but keypoints problem are still.

May I ask where can I fix it?
Thanks very much.
![test_rgb (2)](https://user-images.githubusercontent.com/48346200/125218811-41e08f00-e2f6-11eb-9802-d54a97cd1381.jpg)
![test_rgb (1)](https://user-images.githubusercontent.com/48346200/125218829-49079d00-e2f6-11eb-9748-ed4fadc6a55a.jpg)
![123240209-b0f66f00-d512-11eb-9d6a-d688d4fc9de5](https://user-images.githubusercontent.com/48346200/125218839-4d33ba80-e2f6-11eb-982c-251dd11a7b15.jpg)

**Comment by ethnhe** [comment]
Check that the coordinates of the keypoints in the original object coordinate system are in m, and the translation from the object coordinate system to the camera coordinate system, as well as the scene point clouds, are also in m. Is the distance from the camera to the object about 5m? If so, maybe the keypoints or the translation in your cases is in mm, which should be converted to be in m.

**Comment by Ultraopxt** [comment]
Thanks

**Comment by ghost** [comment]
Hey @qingweihk, have you found a solution (which lines/file should we pay attention to) ?
Thanks for your help
