### ISSUE TITLE
diameter of YCB models

### ISSUE THREAD

**Issue by shockjiang** [ethnhe/PVN3D#88]
Hi, I'm reading the code and try to re-produce your results. As your paper said, AUC is calculated based on the offset distance less than 10 percents of its diameter. However,  when the code calculate the AUC, it seems that a fixed value is used (0.1):
- https://github.com/ethnhe/PVN3D/blob/9a5481a82af4eb89fa8e0ab10ba22b9077b4652e/pvn3d/lib/utils/basic_utils.py#L597
- https://github.com/ethnhe/PVN3D/blob/9a5481a82af4eb89fa8e0ab10ba22b9077b4652e/pvn3d/lib/utils/pvn3d_eval_utils.py#L260

Does I got it right, or I missed something?

Thank you.

**Comment by shockjiang** [comment]
@ethnhe  could you leave me a quick response. I'm kinda hurry to this work.

**Comment by shockjiang** [comment]
@ethnhe any suggestion?

**Comment by ethnhe** [comment]
As illustrated in our paper, the AUC on the YCB-Video is obtained by varying the distance threshold following PoseCNN[52] and DenseFusion[50], the maximum threshold of which is 0.1. Our python code is consistent with their  [Matlab code](https://github.com/yuxng/YCB_Video_toolbox/blob/d08b645d406b93a988087fea42a5f6ac7330933c/plot_accuracy_keyframe.m#L149).

For the metric on the LineMOD dataset, we report the accuracy of distance less than 10% of the object's diameter (ADD-0.1d) following *Model based training, detection and pose estimation of texture-less 3d objects in heavily cluttered scenes.* the same setting in all other baselines in the table.
