### ISSUE TITLE
what different between v1 and v2?

### ISSUE THREAD

**Issue by EasonEdison** [ethnhe/PVN3D#9]
Hello, thank you for your work.
I find the score of Linemod's ADD(S) (Table 3) in v2 is better than v1, have you made any changes?

![image](https://user-images.githubusercontent.com/31425634/78657959-1ce3bc00-78fc-11ea-9719-27964d65b478.png)

![image](https://user-images.githubusercontent.com/31425634/78657918-089fbf00-78fc-11ea-8396-e0df2aae6008.png)

**Comment by ethnhe** [comment]
In v1, we report the ADD-(S) AUC as on the YCB-Video Dataset, which is a harder metric. In v2, we report the ADD-(S) < 0.1 object diameter accuracy following other methods on the LineMOD dataset for a fairer comparison, which is an easier metric, so the score of our result is higher.

**Comment by EasonEdison** [comment]
Thank you for your reply.
