### ISSUE TITLE
linemod dataset AUC: not 0.1d but 0.1

### ISSUE THREAD

**Issue by shockjiang** [ethnhe/PVN3D#97]
Hi, I noticed that you code calculate on AUC ADD 0.1d may not be the 0.1d, but 0.1m instead: https://github.com/ethnhe/PVN3D/blob/d7c2084e82687e4f5fdd383cf69d3df7c3ee379e/pvn3d/lib/utils/pvn3d_eval_utils.py#L298

according to the above code, the threshold is set to 0.1. did I miss something?

@ethnhe

**Comment by ethnhe** [comment]
Yes, the AUC metric is from the YCB-V dataset with the largest threshold 0.1 m. But all methods on LineMOD are evaluated on the < 0.1 d ACC, [0.1d ACC](https://github.com/ethnhe/PVN3D/blob/d7c2084e82687e4f5fdd383cf69d3df7c3ee379e/pvn3d/lib/utils/pvn3d_eval_utils.py#L314), following previous work.

**Comment by shockjiang** [comment]
got it. AUC's threshold for both YCB and Linemod is 0.1m.  ACC threshold for Linemod is 0.1d, for YCB 0.1. Right?

**Comment by ethnhe** [comment]
Mostly right, but on the YCB there is no < 0.1 m ACC, instead, there is an ADDS < 2cm ACC metric introduced by DenseFusion. But that metric is much easier than the AUC metric. I remembered we got nearly 99% on that metric.
